---
# tasks file for hostconfig
- name: Hello World
  debug:
    msg: "Hello world from {{ meta.name }} in the {{ meta.namespace }} namespace."

- name: Message
  debug:
    msg: "Message: {{ message }}"

#- name: DISPLAY THE HOST VARS
#  debug:
#    msg: "The host variable is {{ hostvars }}."
   
- name: DISPLAY HOST DETAILS
  debug:
    msg: "And the kubernetes node name is {{ kube_node_name }}, architecture is {{ architecture }} and kernel version is {{ kernel_version }}"

- name: CREATING A FILE
  shell: "hostname > /home/sirisha/testing; date >> /home/sirisha/testing;cat /home/sirisha/testing;sleep 5"
  register: output

- debug: msg={{ output.stdout }}

- name: ECHO HOSTNAME
  shell: hostname
  register: hostname

- debug: msg={{ hostname.stdout }}
