---
# tasks file for hostconfig
- name: Hello World
  debug:
    msg: "Hello world from {{ meta.name }} in the {{ meta.namespace }} namespace."

- name: Message
  debug:
    msg: "Message: {{ message }}"