apiVersion: hostconfig.airshipit.org/v1alpha1
kind: HostConfig
metadata:
  name: example6
spec:
  # Add fields here
  host_groups:
   - name: "kubernetes.io/role"
     values:
      - "master"
      - "worker"
  sequential: true
  stop_on_failure: true
