apiVersion: hostconfig.airshipit.org/v1alpha1
kind: HostConfig
metadata:
  name: example4
spec:
  # Add fields here
  host_groups:
   - name: "topology.kubernetes.io/zone"
     values:
      - "us-east-1a"
      - "us-east-1b"
   - name: "kubernetes.io/role"
     values:
      - "master"
      - "worker"
  sequential: true
  match_host_groups: true
