apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hostconfigs.hostconfig.airshipit.org
spec:
  group: hostconfig.airshipit.org
  names:
    kind: HostConfig
    listKind: HostConfigList
    plural: hostconfigs
    singular: hostconfig
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
