---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airship-host-config
spec:
  replicas: 1
  selector:
    matchLabels:
      name: airship-host-config
  template:
    metadata:
      labels:
        name: airship-host-config
    spec:
      serviceAccountName: airship-host-config
      containers:
        - name: airship-host-config
          # Replace this with the built image name
          image: "docker.io/port/airship-host-config:latest"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          # add inventory in here, and its used.
          - mountPath: /opt/ansible/inventory
            name: inventory
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "airship-host-config"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: ANSIBLE_INVENTORY
              value: /opt/ansible/inventory
      volumes:
        - name: runner
          emptyDir: {}
        - name: inventory
          emptyDir: {}
